### ISSUE TITLE
Support "composition entity"

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk-wskdeploy#101]
Use case "[Data Processing with MessageHub](https://github.com/IBM/ogs-data-processing-messagehub)" needs an action sequence. We should support `composition entity` in wskdeploy.

Sample:
```
my_action_sequence:
    type: sequence
    sequence:
        - action_1
        - action_2
        - action_3
    inputs:
        simple_input_string: string
    outputs:
        annotated_output_string: string
```
