### ISSUE TITLE
Why are triggers and rules under package in manifest.yml?

### ISSUE THREAD

**Issue by jzaccone** [openwhisk/openwhisk-wskdeploy#132]
From the OpenWhisk getting started [documentation](https://console.ng.bluemix.net/docs/openwhisk/openwhisk_triggers_rules.html#openwhisk_triggers):
>Triggers cannot be created inside a package; they must be created directly under a namespace.

So why are triggers and rules underneath package in manifest.yml?

```
package:
  actions:
  ...
  triggers:
    ...
  rules:
    ...

```

**Comment by mrutkows** [comment]
Packages are compositional units, they can be composed into other packages (and form applications or services) and provide linkage to larger Orchestration templating, much as what you see in AWS Cloud Formation.

**Comment by mrutkows** [comment]
In addition, packages are units of delivery (catalog) and can be versioned, ascribed metadata, etc. as a whole.

**Comment by rabbah** [comment]
I think john's point is that you can't create a trigger or rule inside a package so that's at odds with the principles you just outlined.

**Comment by mrutkows** [comment]
@rabbah I see.  Semantically, we have a conflict then since we established Package to mean a collection of Actions; whereas, we were trying to use it for a broader "packaging" of related whisk entities for publishing.  We have discussed using the term "service" or "bundle" (or "application" which was deemed too broad).  Good time to discuss again.

**Comment by jzaccone** [comment]
Good question.

I feel like this abstraction should extend to the OpenWhisk project itself. Shouldn't the goal of the wskdeploy tool to mirror the abstractions defined on the OpenWhisk platform?

In a way, these things (rules, feeds, triggers) are all associated if they are defined in the same manifest.yml file. Since they aren't reusable in the OpenWhisk platform itself, whats the advantages of having another layer that OW doesn't understand?

(I haven't been working on OW that long, just throwing out ideas based on what I have learned so far)

**Comment by paulcastro** [comment]
wskdeploy assume everything is associated to a package, even though this is not true for triggers in rules.  I did some internal refactoring (I changed the data structure so that triggers and rules are no longer contained in a package struct) because of this issue.  However, this isn't surfaced in the Manifest.  My current thought is that containment in a package is a useful abstraction to provide a default scope when writing out a manifest file.  Basically, can we reduce typing. For example, right now you can write:

```
package:
  name: MyPackage
  actions:
    greeting:
      inputs:
        name: name
          type: string
 triggers:
      myTrigger
 rules:
    myRule:
      trigger: myTrigger
      action: greeting
```

In the actual deployment, we deploy `MyPackage/greeting`, `myTrigger`, 'myRule`.   However, we don't make the developer write out `MyPackage/greeting` in the rule definition.  We just assume that any entity that doesn't explicitly state a package is contained in MyPackage.

I believe this still works when we add the dependency key (issue #41).  In this case, we could have a dependent package named `YourPackage`.  We could use the `greeting` action declared in `YourPackage`:
```
package:
  name: MyPackage
  dependencies:
     YourPackage:
           git: https://somegit
  actions:
    greeting:
      inputs:
        name: name
          type: string
 triggers:
      myTrigger
 rules:
    myRule:
      trigger: myTrigger
      action: greeting
   yourRule:
      trigger: myTrigger
      action: YourPackage/greeting
```

I don't know how you might reference a trigger in a dependent package in a unique way right now since internally we don't support triggers in packages.  We could just modify the trigger name somehow?
