### ISSUE TITLE
Support action location to be a directory (ZIP support)

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk-wskdeploy#136]
If the action location is a folder, wskdeploy should zip all files under this folder and create the action whose source file is a zip file.

e.g.
```
  actions:
    mhpost-action:
      version: 1.0
      location: actions/mhpost/
      runtime: nodejs@6
```
