### ISSUE TITLE
Support inline parameter binding in manifest file

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk-wskdeploy#146]
Currently, parameter binding can only be done in a deployment file.  It should be possible to do in-line parameter binding in the manifest, especially for values that are set by the developer and not intended to be changed.

One possible change is to add a value to the schema "inputs" key:

```
actions:
   myAction:
        inputs:
             myParam:
                  type: string
                  value: "Hello World!" 
            anotherParam:
                  type: int
                  value: 1
```

However, we also allow simple name value pairs without types in the deployment file.  We could allow the same in the manifest without using the schema keys:

```
actions:
   myAction:
       parameters:
            myParam: "Hello World"
            anotherParam: 1
```

**Comment by paulcastro** [comment]
My preference is the second option.

**Comment by mrutkows** [comment]
This is supported in the 0.8.3 Packaging Spec. as the first "use case" for hello world: Manifest Files:

**Manifest files**
_Example 1: No parameter descriptions_
```
helloworld:
  version: 1.0
  license: Apache-2.0
  actions:
    hello:
      version: 1.0
      function: src/hello/hello.js
      inputs:
        personName: string
      outputs:
        greeting_string: string
```

**Comment by paulcastro** [comment]
I'd like a simpler approach where the version of the package applies to the entities so we don't need to explicitly assign a version number to actions, triggers, rules.

**Comment by paulcastro** [comment]
Inferred types would be good.  The inputs in the YAML file get converted into a JSON based request body underneath the covers before calling the OpenWhisk REST API so any inference we make explicit in the spec should follow the JSON type inference rules.

**Comment by paulcastro** [comment]
If we overload the inputs/outputs section to include values, I see two options.

**Option 1: Preserve existing keys and add a value key**
```
actions:
    hello:
      version: 1.0
      function: src/hello/hello.js
      inputs:
             name:
                  type: string
                  value: Paul
 ```
**Option 2: Allow name value pairs as inputs**
```actions:
    hello:
      version: 1.0
      function: src/hello/hello.js
      inputs:
             name: Paul
```

Would we allow mixing and matching of the two? Or are they mutually exclusive.  One problem is not all inputs will take parameter values.  If at some point in the future we need to know all the inputs, what is the best way to handle that case?
