### ISSUE TITLE
In testcases, manifest files with input/output value 'string' treat it as default value, not type specification

### ISSUE THREAD

**Issue by mlinnem** [openwhisk/openwhisk-wskdeploy#172]
In manifest files, when specifying input and output parameters, the value 'string' was expected to be treated as a type specification, but it is instead treated as a default value.

```
/[manifest.yaml/]
helloworld:
      version: 1.0
      location: src/greeting2.js
      runtime: nodejs:6
      inputs:
        name: string
        place: string
      outputs:
        payload: string

```
```
../../../wskdeploy -m manifest.yaml
wsk action invoke helloworld/helloworld -p name Micah -b
```

Expected Result:
`"Hello, Micah from !"
`
Actual Result:

`"Hello, Micah from string!"`

Either this is a bug, or else it might be better make the value something more like "some_string" or "default_value" or something along those lines, to clarify the purpose.
