### ISSUE TITLE
Add $ notation to the manifest file

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk-wskdeploy#174]
Allow values to be set in the YAML files using $ notation. 

```
actions:
   myAction:
        inputs:
            myParam: $MY_VALUE
```

First iteration: $ variables set to values read from environment.

Second iteration: support a properties file, like local.env
