### ISSUE TITLE
Add code to support api-experimental using Option 1 grammar

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-wskdeploy#187]
Reference: https://github.com/openwhisk/openwhisk-wskdeploy/issues/102

Please assume Option 1 grammar and implement as Daisy proposed:

Option 1

The goal of API Gateway is to expose actions via RESTful urls. So the exposed RESTful urls could be properties (or sub elements) of actions. A new property ( or a sub element) is added to action element or other elements, e.g. action sequence and etc.

The property ( or sub elements) can be put in manifest file or deployment file. Both are OK. Below are two samples. The first one is using sub element. The second one is using properties.

Sample:

```
actions:
      fire:
        location: actions/fire/index.js
        inputs:
          triggerName:
            type: string
        exposedUrl:
            url: /whiskbot/slack-event
            verb: post

sequences:
      newbot: 
        actions: oauth/login, decrypt, newbot-setup
        exposedUrl: get /whiskbot/newbot
        exposedUrl: get /whiskbot/anothernewbot
```

**Comment by mrutkows** [comment]
@lzbj @daisy-ycguo Daniel @krook asked that this be raised to high priority for the getting started use cases that will be available next week.

**Comment by lzbj** [comment]
@mrutkows , can we make the exposedUrl consistent like:

actions:
      fire:
        location: actions/fire/index.js
        inputs:
          triggerName:
            type: string
        exposedUrl: post /whiskbot/slack-event

sequences:
      newbot: 
        actions: oauth/login, decrypt, newbot-setup
        exposedUrl: get /whiskbot/newbot
        exposedUrl: get /whiskbot/anothernewbot

**Comment by mrutkows** [comment]
@lzbj Can you format your suggested change (use the <> code option) so I can see indentations?

**Comment by mrutkows** [comment]
Upon re-reading your comments and review of the experimental API (and considering the ability to "import" manifests from other sources to create your own APIs) I too now agree Option 2 (from Daisy) is the best option.  

Note: I think we can support an Option 1 grammar in the future (with simple notation)

Option 2 (revised) grammar using the "book club" example:

```
$ wsk api-experimental create -n "Book Club" /club /books get getBooks
$ wsk api-experimental create /club /books post postBooks
$ wsk api-experimental create /club /books put putBooks
$ wsk api-experimental create /club /books delete deleteBooks
```
the above would translate to the following grammars in the pkg. spec. to a new-top level keyname "apis" in the manifest:

Full grammar:
```
apis:   # new top-level key for defining groups of named APIs
    book-club:  
      description: Book Club
      basepath: /club  #shared basepath
      path: /books   # shared path
      actions:
         getBooks:
             verb: get
         postBooks:
             verb: post
         putBooks:
              verb: put
         deleteBooks:
             verb: delete
```

A somewhat simplified grammar :
```
apis:
    book-club:
        actions:
            getBooks: get  /<base
            postBooks: post
            putBooks: put
            deleteBooks: delete
```

I would still like to see API assignment/association (as in Option 1) under each action (seems simplest to me), something like:

```
actions:
    getBooks: # action
        location: ...
        ...
        api: <verb> <basePath>/<path>
```

Please comment.
