### ISSUE TITLE
Update spec. to reflect API (gateway) grammar

### ISSUE THREAD

**Issue by mrutkows** [openwhisk/openwhisk-wskdeploy#201]
Option 2 (revised) grammar using the "book club" example:

```
$ wsk api-experimental create -n "Book Club" /club /books get getBooks
$ wsk api-experimental create /club /books post postBooks
$ wsk api-experimental create /club /books put putBooks
$ wsk api-experimental create /club /books delete deleteBooks
```

the above would translate to the following grammars in the pkg. spec. to a new-top level keyname "apis" in the manifest:

Full grammar:

```
apis:   # new top-level key for defining groups of named APIs
    book-club:  
      description: Book Club  # optional
      basepath: /club  # optional, shared basepath
      path: /books   # optional, shared path
      # TBD: This structure allows for more "shared" properties in the future.
      actions:
         getBooks:
             verb: get
             # This grammar allows for more keys in the future
         postBooks:
             verb: post
         putBooks:
              verb: put
         deleteBooks:
             verb: delete
```

A somewhat simplified grammar :

```
apis:
    book-club:
        actions:
            # if single line (only key: value syntax), assume <verb> is the value
            getBooks: get  # <verb>
            postBooks: post 
            putBooks: put
            deleteBooks: delete 
```

I would still like to see API assignment/association (as in Option 1) under each action (seems simplest to me), something like:

```
actions:
    getBooks: # action
        location: ...
        ...
        api: <verb> <basePath>/<path>
```

Please feel free to comment.
