### ISSUE TITLE
Unable to parse baseURL in the application section of deployment.yml

### ISSUE THREAD

**Issue by houshengbo** [openwhisk/openwhisk-wskdeploy#205]
This is the a valid yml file we ought to parse:

```
application:
  name: wskdeploy-samples
  namespace: guest
  credential: <key>
  baseUrl: https://172.17.0.1/api
```
However, baseUrl value is unable to be picked up by the parser. Values from namespace and credential can be parsed, but the value of baseUrl is nil, though the baseUrl is not empty.
@lzbj @paulcastro This should be a valid bug.
