### ISSUE TITLE
Add manifest for `wskdeploy` itself

### ISSUE THREAD

**Issue by lionelvillard** [openwhisk/openwhisk-wskdeploy#225]
Since `wskdeploy` can be deployed, we should provide a minimal manifest: 

```
package:
  name: wskdeploy
  version: 0.4.0
  description: Utility for deploying and managing Apache OpenWhisk packages and projects
  license: Apache-2.0
  repositories:
    - url: http://github.com/openwhisk/openwhisk-wskdeploy
  actions:
    exec:
      location: actions/exec/exec.zip
      runtime: blackbox
```

Notice the `exec` location pointing to a generated zip file, which needs to be checked in so that it can be included by other OpenWhisk projects.

An alternative solution is to have `script` section with commands to generate the zip file. 

Ideas?
