### ISSUE TITLE
Sequence annotations are ignored

### ISSUE THREAD

**Issue by lionelvillard** [openwhisk/openwhisk-wskdeploy#246]
Manifest causing the error:
```
package:
  name: test-public 
  sequences:
    protected:
      actions: test-public/web,test-private/sensitive
      annotations:
         web-export:true
  ...
```

I'm getting this error
```
Got error creating action with error message: Sequence component does not exist. (code 185541) and error code: 144.
```
