### ISSUE TITLE
Create Action from a ZIP file

### ISSUE THREAD

**Issue by pritidesai** [openwhisk/openwhisk-wskdeploy#250]
We have a use case of creating an action from a zip file after running set of bash commands, e.x: when an action directory contains index.js and package.json for node runtime:

```
ls actions/my-action/
index.js
package.json
cd actions/my-action
npm install
zip -rq action.zip *
wsk action create my-action --kind nodejs:6 action.zip
```

[Here](https://github.com/IBM/openwhisk-serverless-apis) is the OpenWhisk Serverless repo.

Here the question is, how do we support this kind of workflow without expecting users to run those bash commands before initiating wskdeploy? We can define a new notation for such use case. Right now action has roughly following grammar:

```
actions:
  hello:
    version: 1.0
    function: src/hello/hello.js
    runtime: nodejs
    inputs:
      personName: Bob
    outputs:
      greeting_string: string
```

Either we overload existing grammar say, "If action source has a filename ending in .zip and runtime nodejs, wskdeploy packages dependencies (npn install) and creates a zip file before creating an action." Or Introduce new key to support "kind" flag. 

Whatever approach we decide, we have to make this generic and include all possible runtimes.

**Comment by lzbj** [comment]
This issue is sound more like we support run command line from wskdeploy? @pritidesai , so what about:
```
actions:
  hello:
    version: 1.0
     command: npm install
    location: src/hello/  #action folder
    runtime: nodejs
    inputs:
      personName: Bob
    outputs:
      greeting_string: string
```

For the use case you mentioned we only need the npm install command, because we supported create zip action from folder.  Any way, the user needs to make sure the npm install command is supported on the os, and there is packages.json under the folder.

**Comment by lzbj** [comment]
@pritidesai @mrutkows , do you have any feedback on this issue? We can use os.exec to support run commands.

**Comment by pritidesai** [comment]
Instead of having users specify custom bash commands in a separate `command` YAML key, wskdeploy implicitly installs dependent packages and zip them in a folder, for example, wskdeploy runs through following steps with this manifest file:

```
package:
    name: cat-get
    actions:
        cat-get-action:
            location: actions/cat-get-action
            runtime: nodejs:6
            inputs:
                MYSQL_HOSTNAME: $MYSQL_HOSTNAME
                MYSQL_USERNAME: $MYSQL_USERNAME
                MYSQL_PASSWORD: $MYSQL_PASSWORD
                MYSQL_DATABASE: $MYSQL_DATABASE
```

- Check if `package.json` file exists in action folder (`actions/cat-get-action`) and runtime is `nodejs`, run `npm install` so that all the necessary modules are installed in `actions/cat-get-action/node_modules`. 
- Zip the entire folder  `actions/cat-get-action` and create a zip file `actions/cat-get-action.zip`
- Use this zip file `actions/cat-get-action.zip` to create an action `cat-get-action`.

For now, we are going to implement implicit behavior for `nodejs` runtime only. We can update rest of the runtimes as needed. Thoughts?

@lzbj @mrutkows @daisy-ycguo @houshengbo @paulcastro 

The main rationale behind this kind of design is to avoid having random and destructive bash commands in a manifest file.

P.S.

We need #269 fixed so that zipping an entire folder can be supported.
