### ISSUE TITLE
Add support to manage dependencies

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk-wskdeploy#41]
The current tool cannot reference other OpenWhisk packages as dependencies.  At a minimum we should be able to pull in and reference entities in other packages w/o requiring the developer to copy the source code.  This requires:

- create a module to parse dependency graph and validate it
- create feature to download/obtain dependencies into the current project path and be able to reference these from inside the manifest and deployment yaml files.

This is a large task and likely should be broken up into multiple issues.

As a starting step let's propose:
- support for getting a Github-based  OpenWhisk package
- mange a semantic version applied to an entire deployment (as opposed to individual entities)

**Comment by lzbj** [comment]
@paulcastro ,very interesting features, please split it into smaller issues, so we could help if possible.

**Comment by paulcastro** [comment]
When someone pushes a package to a repo, there should be a default package name for it that is unique.  We currently don't have a scheme for this though we could borrow from other dependency management frameworks.  For instance, we could use a URL as the canonical name for the package.

When someone integrates a package from a repo, they should have the option to override the default name.  

An example of support for this kind of model is how Go treats imports.

**Comment by lionelvillard** [comment]
After weighting several options, I would use a shorten (no protocol) URL as the canonical name for the package as you suggested. This has several advantages:
- it is unique
- no need to override the default name to avoid conflict
- no need to go through a global naming service to guarantee the package name uniqueness
- easier server-side deployment
- the name can be used to directly locate the source code 
 
The only minor problem is the package name cannot contains `/` characters, which has a simple solution.

**Comment by paulcastro** [comment]
Thinking about package bindings, perhaps something like this:

```
package:
   name: myPackage
   dependencies:
           Cloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  binding-name: myCloudant
                  inputs: 
                         param1: value1
 ```

The above assumes there is an OpenWhisk package called `Cloudant`, it's location is "whisk.system", and I want to refer to it as `myCloudant` inside this manifest file.

I'm not sure how to handle name uniqueness for package names.  One option is to follow go's model, and use a internet style name based on whisk.system or GitHub repos:

```
package:
   name: myPackage
   dependencies:
           /whisk.system/cloudant:
                  version 1.2
                  binding-name: myCloudant
                  inputs: 
                         param1: value
          github.com/openwhisk/openwhisk-client-swift
                  version .02.2
                  binding-name: mySwift
 ```

If you don't specify a binding-name, then you refer to the package using whatever the package itself specifies, e.g. /whisk.system/cloudant refers to itself as "cloudant" in its package manifest.

**Comment by paulcastro** [comment]
Another option is to specify the binding name upfront, and not have a binding-name key.
```
package:
   name: myPackage
   dependencies:
           myCloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  inputs: 
                         param1: value1
 ```
If I want to use the default name (i.e. not specify a binding) then I just use the default name:

```
package:
   name: myPackage
   dependencies:
           cloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  inputs: 
                         param1: value1
 ```

**Comment by lionelvillard** [comment]
For uniqueness, see https://github.com/openwhisk/openwhisk-wskdeploy/issues/41#issuecomment-285750992

The first option does not work, as property keys in YAML must be unique and the same package can be bound multiple times. Option 2 might be clearer.

**Comment by lzbj** [comment]
so we are all agree with this solution https://github.com/openwhisk/openwhisk-wskdeploy/issues/41#issuecomment-285799805, Ok, i'll investigate it and put it a high prio one, as our 101 use cases need to use dependencies.

**Comment by paulcastro** [comment]
@lzbj I can reassign to you - thanks.  We agree on option 2 (see below).  

For iteration 1: we will only support binding so location should be the package we are binding to.

In the next iteration, we will can add support for remote GitHub URLs.  

```
package:
   name: myPackage
   dependencies:
           myCloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  inputs: 
                         param1: value1
          mySwift:
                  location:  github.com/openwhisk/openwhisk-client-swift
package:
   name: myPackage
   dependencies:
           myCloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  inputs: 
                         param1: value1
          mySwift:
                  location:  github.com/openwhisk/openwhisk-client-swiftpackage:
   name: myPackage
   dependencies:
           myCloudant:
                  version 1.2
                  location: /whisk.system/cloudant
                  inputs: 
                         param1: value1
          mySwift:
                  location:  github.com/openwhisk/openwhisk-client-swift
```

**Comment by lzbj** [comment]
Ok, sure, got it. thanks.

**Comment by paulcastro** [comment]
I tried using `url` and `source` as keys to distinguish between GitHub and system bindings.  I'm not 100% this is correct and may refactor to overload `location` with two meanings.

```
package:
   name: myPackage
   dependencies:
           myCloudant:
                  version 1.2
                  source: /whisk.system/cloudant
                  inputs: 
                         param1: value1
          mySwift:
                  url:  https://github.com/openwhisk/openwhisk-client-swift
```
