### ISSUE TITLE
Support multiple packages deployment in a single command

### ISSUE THREAD

**Issue by daisy-ycguo** [openwhisk/openwhisk-wskdeploy#56]
We need to discuss how to support multiple packages deployment in a single command. There are two options:

- add multiple packages in a single manifest file
- use multiple manifest files, 1 package per a manifest

Let's discuss the solution here.

**Comment by paulcastro** [comment]
I can open the discussion with a level-set.  In the current model, the manifest file corresponds to the local resources a developer will create as part of their project.  There is a limitation now that the manifest file assumes there will only be a single package. I had assumed the packages correspond to a developer organizing construct, i.e. the developer just wants to group related entities together.  However, if we assume that packages are a construct to declare re-usable "modules", that are either stand-alone, or be used as part of a larger application, then the limitation on 1 package in the manifest file may be fine. 

If we assume modules, then:
1. Do we explicitly support the default "_" package as a valid name for a package? In other words, if we allow the developer to name the package "_",  this will install things in OpenWhisk at the root level of the namespace (i.e the qualified name is /namespace/_/entityName").

2. The manifest file is used to describe the wiring of OpenWhisk entities that are local to the current package -- I believe the deployment file is then used for 2 things:
   i) parameter binding to the local resources, i.e. set values for input parameters
  ii) eventually, describe the wiring of the local package to external dependencies.

For the second usage, we definitely need support for multiple packages in the deployment descriptor.  Perhaps we can adopt the model of Go dependencies, where the default is to take the name of the package in the manifest file, but the developer can override this in the deployment descriptor:

As a crude example, assume we add a dependencies section for the deployment descriptor:

```
dependencies:
   location: "github.com/openwhisk/mypackage" #will install as "mypackage" derived from manifest
   location: "github.com/openwhisk/anotherPackage" . #will install as "myCustomName"
                   name: myCustomName
```
